-- VidyaSetu current schema baseline exported from local attendance_db.
-- Day 22 Step 2B reference schema.
-- Do NOT place this file in src/main/resources/db/migration for the existing local attendance_db,
-- because Flyway already baselined that database at version 1 and this schema would try to recreate existing tables.
-- Use this file later for fresh staging/local database validation.

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
                                  id bigint NOT NULL,
                                  credentials_active boolean NOT NULL,
                                  display_name character varying(255),
                                  force_password_change boolean NOT NULL,
                                  password character varying(255),
                                  role character varying(255),
                                  school_code character varying(4),
                                  school_id bigint,
                                  school_name character varying(255),
                                  teacher_id bigint,
                                  teacher_name character varying(255),
                                  username character varying(255)
);


--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance (
                                   id bigint NOT NULL,
                                   attendance_date date,
                                   class_name character varying(255),
                                   section character varying(255),
                                   status character varying(255),
                                   subject_name character varying(255),
                                   teacher_id bigint,
                                   teacher_name character varying(255),
                                   student_id bigint NOT NULL,
                                   CONSTRAINT attendance_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'LATE'::character varying])::text[])))
);


--
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
                                              installed_rank integer NOT NULL,
                                              version character varying(50),
                                              description character varying(200) NOT NULL,
                                              type character varying(20) NOT NULL,
                                              script character varying(1000) NOT NULL,
                                              checksum integer,
                                              installed_by character varying(100) NOT NULL,
                                              installed_on timestamp without time zone DEFAULT now() NOT NULL,
                                              execution_time integer NOT NULL,
                                              success boolean NOT NULL
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
                                      id bigint NOT NULL,
                                      class_name character varying(255),
                                      created_at timestamp(6) without time zone,
                                      message character varying(255),
                                      read boolean NOT NULL,
                                      role character varying(255),
                                      school_id bigint,
                                      section character varying(255),
                                      title character varying(255),
                                      type character varying(255),
                                      user_id bigint
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_branding; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_branding (
                                        id bigint NOT NULL,
                                        address character varying(255),
                                        email character varying(255),
                                        logo_url character varying(255),
                                        phone character varying(255),
                                        primary_color character varying(255),
                                        principal_name character varying(255),
                                        school_name character varying(255),
                                        secondary_color character varying(255),
                                        short_name character varying(255),
                                        tagline character varying(255),
                                        watermark_text character varying(255),
                                        website character varying(255)
);


--
-- Name: school_branding_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_branding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_branding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_import_staging_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_import_staging_records (
                                                      id bigint NOT NULL,
                                                      academic_year character varying(255),
                                                      import_batch_id character varying(255),
                                                      record_key character varying(255),
                                                      rolled_back_at timestamp(6) without time zone,
                                                      row_json text,
                                                      school_code character varying(4) NOT NULL,
                                                      sheet_name character varying(255),
                                                      staged_at timestamp(6) without time zone,
                                                      status character varying(255),
                                                      upload_id bigint NOT NULL,
                                                      workbook_row_number integer NOT NULL
);


--
-- Name: school_import_staging_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_import_staging_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_import_staging_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_import_uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_import_uploads (
                                              id bigint NOT NULL,
                                              academic_year character varying(255),
                                              checksum character varying(255),
                                              committed boolean NOT NULL,
                                              committed_at timestamp(6) without time zone,
                                              error_count integer NOT NULL,
                                              file_name character varying(255),
                                              import_batch_id character varying(255),
                                              import_type character varying(255),
                                              lifecycle_message character varying(255),
                                              preview_json text,
                                              rolled_back boolean NOT NULL,
                                              rolled_back_at timestamp(6) without time zone,
                                              school_code character varying(4) NOT NULL,
                                              staged_row_count integer NOT NULL,
                                              status character varying(255),
                                              total_rows integer NOT NULL,
                                              total_sheets integer NOT NULL,
                                              uploaded_at timestamp(6) without time zone,
                                              uploaded_by_role character varying(255),
                                              warning_count integer NOT NULL,
                                              workbook_data_json text
);


--
-- Name: school_import_uploads_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_import_uploads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_import_uploads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_notices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_notices (
                                       id bigint NOT NULL,
                                       active boolean NOT NULL,
                                       created_at timestamp(6) without time zone,
                                       created_by character varying(255),
                                       message character varying(2000),
                                       notice_type character varying(255),
                                       school_id bigint,
                                       target_role character varying(255),
                                       title character varying(255)
);


--
-- Name: school_notices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_notices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_notices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_onboarding_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_onboarding_requests (
                                                   id bigint NOT NULL,
                                                   activated_at timestamp(6) without time zone,
                                                   activated_by character varying(255),
                                                   admin_initial_password character varying(255),
                                                   admin_username character varying(255),
                                                   approved_at timestamp(6) without time zone,
                                                   approved_by character varying(255),
                                                   city character varying(255),
                                                   contact_email character varying(255),
                                                   contact_person character varying(255),
                                                   contact_phone character varying(255),
                                                   credentials_issued_at timestamp(6) without time zone,
                                                   credentials_issued_by character varying(255),
                                                   expected_students integer,
                                                   expected_teachers integer,
                                                   notes character varying(2000),
                                                   pilot_activated_at timestamp(6) without time zone,
                                                   pilot_enabled_by character varying(255),
                                                   preferred_role character varying(255),
                                                   principal_initial_password character varying(255),
                                                   principal_username character varying(255),
                                                   reference_id character varying(40) NOT NULL,
                                                   rejected_at timestamp(6) without time zone,
                                                   request_type character varying(24) NOT NULL,
                                                   reserved_at timestamp(6) without time zone,
                                                   review_notes character varying(2000),
                                                   school_id character varying(4),
                                                   school_name character varying(255) NOT NULL,
                                                   state character varying(255),
                                                   status character varying(24) NOT NULL,
                                                   status_history character varying(4000),
                                                   submitted_at timestamp(6) without time zone,
                                                   submitted_by character varying(255),
                                                   updated_at timestamp(6) without time zone
);


--
-- Name: school_onboarding_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_onboarding_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_onboarding_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.students (
                                 id bigint NOT NULL,
                                 admission_number character varying(255),
                                 class_name character varying(255),
                                 name character varying(255),
                                 roll_number character varying(255),
                                 section character varying(255)
);


--
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher_assignment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_assignment (
                                           id bigint NOT NULL,
                                           class_name character varying(255),
                                           section character varying(255),
                                           subject_name character varying(255),
                                           teacher_id bigint,
                                           teacher_name character varying(255)
);


--
-- Name: teacher_assignment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teacher_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher_leave_enquiries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_leave_enquiries (
                                                id bigint NOT NULL,
                                                admin_remarks character varying(255),
                                                decided_at timestamp(6) without time zone,
                                                from_date date,
                                                leave_type character varying(255),
                                                reason character varying(1000),
                                                requested_at timestamp(6) without time zone,
                                                status character varying(255),
                                                teacher_id bigint,
                                                teacher_name character varying(255),
                                                to_date date
);


--
-- Name: teacher_leave_enquiries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teacher_leave_enquiries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_leave_enquiries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_schedule (
                                         id bigint NOT NULL,
                                         class_name character varying(255),
                                         end_time time(6) without time zone,
                                         replacement_class boolean,
                                         replacement_teacher_id bigint,
                                         replacement_teacher_name character varying(255),
                                         schedule_date date,
                                         section character varying(255),
                                         start_time time(6) without time zone,
                                         status character varying(255),
                                         subject_name character varying(255),
                                         teacher_id bigint,
                                         teacher_name character varying(255),
                                         CONSTRAINT teacher_schedule_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'PLANNED_LEAVE'::character varying, 'UNPLANNED_LEAVE'::character varying, 'REPLACED'::character varying])::text[])))
);


--
-- Name: teacher_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teacher_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workspace_setup_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspace_setup_status (
                                               id bigint NOT NULL,
                                               academic_year character varying(255),
                                               academic_year_completed boolean NOT NULL,
                                               academic_year_end_date date,
                                               academic_year_start_date date,
                                               classes_completed boolean NOT NULL,
                                               completed_steps integer NOT NULL,
                                               created_at timestamp(6) without time zone,
                                               holiday_calendar_completed boolean NOT NULL,
                                               import_locked boolean NOT NULL,
                                               periods_per_day integer,
                                               progress_percent integer NOT NULL,
                                               school_end_time character varying(255),
                                               school_id character varying(4) NOT NULL,
                                               school_name character varying(255),
                                               school_profile_completed boolean NOT NULL,
                                               school_start_time character varying(255),
                                               school_timings_completed boolean NOT NULL,
                                               sections_completed boolean NOT NULL,
                                               subjects_completed boolean NOT NULL,
                                               teachers_completed boolean NOT NULL,
                                               total_steps integer NOT NULL,
                                               updated_at timestamp(6) without time zone,
                                               working_days character varying(255),
                                               working_days_completed boolean NOT NULL
);


--
-- Name: workspace_setup_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workspace_setup_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workspace_setup_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: school_onboarding_requests idx_school_onboarding_reference_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_onboarding_requests
    ADD CONSTRAINT idx_school_onboarding_reference_id UNIQUE (reference_id);


--
-- Name: workspace_setup_status idx_workspace_setup_school_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_setup_status
    ADD CONSTRAINT idx_workspace_setup_school_id UNIQUE (school_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: school_branding school_branding_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_branding
    ADD CONSTRAINT school_branding_pkey PRIMARY KEY (id);


--
-- Name: school_import_staging_records school_import_staging_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_import_staging_records
    ADD CONSTRAINT school_import_staging_records_pkey PRIMARY KEY (id);


--
-- Name: school_import_uploads school_import_uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_import_uploads
    ADD CONSTRAINT school_import_uploads_pkey PRIMARY KEY (id);


--
-- Name: school_notices school_notices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_notices
    ADD CONSTRAINT school_notices_pkey PRIMARY KEY (id);


--
-- Name: school_onboarding_requests school_onboarding_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_onboarding_requests
    ADD CONSTRAINT school_onboarding_requests_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: teacher_assignment teacher_assignment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_assignment
    ADD CONSTRAINT teacher_assignment_pkey PRIMARY KEY (id);


--
-- Name: teacher_leave_enquiries teacher_leave_enquiries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_leave_enquiries
    ADD CONSTRAINT teacher_leave_enquiries_pkey PRIMARY KEY (id);


--
-- Name: teacher_schedule teacher_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_schedule
    ADD CONSTRAINT teacher_schedule_pkey PRIMARY KEY (id);


--
-- Name: attendance uk7sy4g5i205leugwkyoqvkq7u5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT uk7sy4g5i205leugwkyoqvkq7u5 UNIQUE (student_id, attendance_date, teacher_id, subject_name, class_name, section);


--
-- Name: workspace_setup_status workspace_setup_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspace_setup_status
    ADD CONSTRAINT workspace_setup_status_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_import_staging_school_batch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_import_staging_school_batch ON public.school_import_staging_records USING btree (school_code, import_batch_id);


--
-- Name: idx_import_staging_sheet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_import_staging_sheet ON public.school_import_staging_records USING btree (sheet_name);


--
-- Name: idx_import_staging_upload; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_import_staging_upload ON public.school_import_staging_records USING btree (upload_id);


--
-- Name: idx_school_import_upload_checksum; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_school_import_upload_checksum ON public.school_import_uploads USING btree (checksum);


--
-- Name: idx_school_import_upload_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_school_import_upload_school ON public.school_import_uploads USING btree (school_code);


--
-- Name: idx_school_onboarding_school_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_school_onboarding_school_id ON public.school_onboarding_requests USING btree (school_id);


--
-- Name: idx_school_onboarding_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_school_onboarding_status ON public.school_onboarding_requests USING btree (status);


--
-- Name: attendance fk7121lveuhtmu9wa6m90ayd5yg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fk7121lveuhtmu9wa6m90ayd5yg FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- PostgreSQL database dump complete
--
